add judge whether audio exists in oss

diff --git a/models/aliyun_ftasr_api_zh/SBI b/models/aliyun_ftasr_api_zh/SBI
--- a/models/aliyun_ftasr_api_zh/SBI
+++ b/models/aliyun_ftasr_api_zh/SBI
@@ -8,6 +8,7 @@ fi
 scp=$1
 dir=$2
 oss_scp=${dir}/wav_oss.scp
+oss_loss_scp=${dir}/wav_oss_loss.scp
 part_nums=10
 test_time=$(date +"%Y-%m-%d-%H-%M-%S")
 echo "Test starts at "${test_time}
@@ -26,7 +27,16 @@ fi
 
 
 # upload wav to oss
-./upload_wav.py ${scp} ${oss_scp} ${dir} ${test_time}
+./upload_wav.py ${scp} ${oss_scp} ${dir} speechiotest-${test_time}
+
+# check oss wav
+./check_wav.py speechiotest-${test_time} ${oss_scp} ${oss_loss_scp}
+if [ -s ${oss_loss_scp} ];then
+  echo "Not found some audio in oss bucket! Please check" ${oss_loss_scp}
+  exit 1
+else
+  echo "Upload audio successfully. Continue..."
+fi
 
 # split test set 
 awk -vf=${part_nums} -vl="`wc -l $oss_scp`" 'BEGIN{p=int(l/f);q=(l%f);for(n=1;n<=f;n++)a[n]=n*p+((n<=q)?++x:x)}{if(NR>a[i])i++;print > "'$oss_scp'."i}' $oss_scp
@@ -44,4 +54,4 @@ rm -rf ${dir}/raw_rec.txt.*
 rm -rf ${oss_scp}.*
 
 # delete oss bucket
-./del_oss_bucket.py ${dir} ${test_time}
+./del_oss_bucket.py ${dir} speechiotest-${test_time}
